### ISSUE TITLE
Prazo de entrega

### ISSUE THREAD

**Issue by brenndap** [juntossomosmais/frontend-challenge#1]
Olá, gostaria de saber qual o prazo para a entrega do teste.

**Comment by felipefialho** [comment]
Olá @brenndafarinha, idealmente 10 dias. Mas caso precise de mais prazo avisa a gente 😄

**Comment by brenndap** [comment]
Combinado, então. Valeu 😉

**Comment by brenndafarinha** [comment]
Olá, me surgiu uma dúvida em relação ao filtro de usuários por categoria. O que entendi é que preciso filtrar usuários que estejam dentro das coordenadas fornecidas. Na categoria "normal", eu verifico se os usuários estão dentro de uma reta e na categoria "especial", verifico se estão dentro de um polígono. Porém, nenhum dos usuários retornados pela api se enquadram nessas categorias, somente na categoria "trabalhoso". Testei na lógica que eu criei e também com o google maps. Queria saber se entendi o problema de forma correta ou não?
