### ISSUE TITLE
[DÚVIDA] - Porque meu código deve estar privado?

### ISSUE THREAD

**Issue by luan0ap** [juntossomosmais/frontend-challenge#10]
Olá! Como estão?

Achei bacana o desafio e gostaria de implementar ele sem aplicar para a vaga de fato a fim de deixar o projeto público, gostaria de entender porque o código deve estar privado segundo em uma das regras.

**Comment by felipefialho** [comment]
A gente pede pra deixar privado para evitar que decisões, algoritimos, soluções, arquiteturas e etc sejam copiados, o que poderia facilitar a resolução do desafio

Mas na pratica não temos como controlar isso

O que muita gente faz é manter desafios no privado e enviar a resolução para outras empresas durante processos seletivos, dessa forma serve como portfolio
