### ISSUE TITLE
Estudo de caso

### ISSUE THREAD

**Issue by lucaspmarra** [juntossomosmais/frontend-challenge#11]
Boa tarde, navegando pelo GitHub encontrei esse teste.
Para treinar meus conhecimentos, me aventurei a tentar e desenvolver algo dentro dos meus conhecimentos.

O que foi feito:
- Criação de um live proxy para passar pelo bloqueio de CORS;
- GET dos dados com o Axios, passando as props dos dados para conseguir mostrar os dados numa nova página;

Foi meu primeiro projeto utilizando Vue3com Composition API (geralmente utilizo o Vue2 com Options API), sendo assim, foi um desafio pra mim.
Não há uma documentação formal ainda escrita no projeto, entretanto, o projeto pode ser acesso neste link: https://lucaspmarra.github.io/vue3-juntos-somos-mais/
Para tal, utilizei um CI/CD com o Github Actions, para a cada commit, ser realizado a build do projeto e posteriormente criado o GitHub Pages apontado para a pasta dist (padrão).
Projeto foi criado utilizando os padrões ESLint, caso desejem consultar e baixar o código: https://github.com/lucaspmarra/vue3-juntos-somos-mais
Devo avisar que localmente, irá cair no CORS, porque habilitei no meu Proxy apenas meus IPs.
Saliento também que o projeto não está nem perto de estar pronto e muito menos do jeito que eu gostaria...

**Comment by mauriciomutte** [comment]
Fala Lucas, muito legal que o nosso desafio ajudou você a aprender mais, excelente iniciativa! Utilizamos as issues aqui para dúvidas e sugestões. :slightly_smiling_face:  

Sugiro que você siga os passos que estão descritos nas regras do desafio:
1. [Tornar **privado** o repositório do seu desafio](https://github.com/juntossomosmais/frontend-challenge#rules)
2. [Enviar o desafio no e-mail, seguindo o padrão](https://github.com/juntossomosmais/frontend-challenge#sending-the-challenge)
