### ISSUE TITLE
Every rule will cause TRABALHOSO

### ISSUE THREAD

**Issue by bodjay** [juntossomosmais/frontend-challenge#3]
Every region will cause TRABALHOSO if we follow the described case

eg.
minlon: -2.196998 
maxlon: -15.411580

-15.411580  **ins't** greater than -2.196998 

![image](https://user-images.githubusercontent.com/33819657/74550511-43a2f900-4f30-11ea-8d71-a2c94cf4b36a.png)

**Comment by felipefialho** [comment]
😆
