### ISSUE TITLE
Bloqueio por Cors na API

### ISSUE THREAD

**Issue by Natalie9** [juntossomosmais/frontend-challenge#6]
Estou tentando realizar o acesso da Api via axios e encontro um bloqueio de CORS.
``` axios.get('https://jsm-challenges.s3.amazonaws.com/frontend-challenge.json') ```` 

> Access to XMLHttpRequest at 'https://jsm-challenges.s3.amazonaws.com/frontend-challenge.json' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

 Devo adicionar algum header de permissão, ou realizar a requisição de outra forma?

Como solução busquei a API diretamente no browser, copiei os dados para um aquivo json e utilizo de forma estática no projeto, mas acredito não ser a melhor opção.

**Comment by schultz-gabriel** [comment]
Como você resolveu esse problema, Natalie?

**Comment by Natalie9** [comment]
Oie @SchultzGabriel , essa questão faz parte do desafio e buscar formas de contorná-la estão inclusas na avaliação. 
Mas uma dica é: no enunciado do desafio tem uma pista de como resolver 😉
