### ISSUE TITLE
Dúvida Filtro Regiões

### ISSUE THREAD

**Issue by GuiErba** [juntossomosmais/frontend-challenge#7]
Os valores fixos de minLong/minLat/maxLong/maxLat estão todos corretos?
Fiz alguns testes com todos os valores e em sua maioria não retorna nenhum usuário.

Outra dúvida, existe 2 filtros diferentes para o **ESPECIAL**, como isso deverá funcionar? Será duas filtros em uma única opção?

**Comment by HelenDias** [comment]
@GuiiHenriq os valores estão corretos, pode confiar haha 
E a maioria dos filtros deve retornar usuários 🤔 
Sobre o filtro ESPECIAL, pode seguir confiando na sua intuição 😉

**Comment by GuiErba** [comment]
Obrigado @HelenDias
