### ISSUE TITLE
Situação de vagas

### ISSUE THREAD

**Issue by rubensbatista98** [juntossomosmais/frontend-challenge#9]
E aí @felipefialho, tudo bem cara ?

Queria saber se vocês aí da Juntos ainda estão com vagas para Dev. Fron-end ? E se eu posso enviar meu teste finalizado ?

**Comment by felipefialho** [comment]
Opa @rubensbatista98 

Temos duas vagas de Front abertas, pode se inscrever pela Gupy ;) 

- [React](https://juntossomosmais.gupy.io/jobs/631197)
- [Vue](https://juntossomosmais.gupy.io/jobs/631210)
